<a href="https://colab.research.google.com/github/juliaNogueiraC/Estudos-em-Data-Analysis-Python/blob/main/Estudos_em_Data_Analysis_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***NUMPY***


##1. Criando array

In [ ]:
import numpy as np

# Criando um array unidimensional
arr1d = np.array([1, 2, 3, 4, 5])

# Criando uma matriz bidimensional
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

##2. Operações Vetorizadas:


In [ ]:
import numpy as np
# Operações simples em arrays
arr = np.array([1, 2, 3, 4, 5])

# Multiplicação de todos os elementos por 2
result = arr * 2
print(result)
# Adição de 10 a todos os elementos
result = arr + 10
print(result)


[ 2  4  6  8 10]
[11 12 13 14 15]


##3. Indexação e Fatiamento:

In [ ]:
import numpy as np
# Indexação e fatiamento em arrays
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Selecionando elementos de índice 2 a 5
subset = arr[2:6]
print(subset)

# Indexação booleana para selecionar elementos maiores que 5
subset = arr[arr > 5]
print(subset)


[2 3 4 5]
[6 7 8 9]


##4. Funções Matemáticas:

In [ ]:
# Funções matemáticas em arrays
arr = np.array([1, 2, 3, 4, 5])

# Calculando o seno de cada elemento
sin_values = np.sin(arr)
print(sin_values)

# Calculando a média dos elementos
mean_value = np.mean(arr)

print(mean_value)


[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
3.0


##5. Operações estatisticas

In [ ]:
import numpy as np

# Criando um array de dados
dados = np.array([10, 15, 12, 8, 20, 14, 18, 22, 25, 16])

# Calculando a média e o desvio padrão
media = np.mean(dados)
print("media:", media)
desvio_padrao = np.std(dados)
print("desvio padrão", desvio_padrao)

# Encontrando o valor máximo e mínimo
maximo = np.max(dados)
minimo = np.min(dados)
print("max:", maximo)
print("min:", maximo)

media: 16.0
desvio padrão 5.079370039680118
max: 25
min: 25


##6. Trabalhando com Matrizes:

In [ ]:
# Criando uma matriz de dados
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculando a soma das colunas e das linhas
soma_colunas = np.sum(matriz, axis=0)
print("soma das colunas:", soma_colunas)

soma_linhas = np.sum(matriz, axis=1)
print("soma das linhas:", soma_linhas)


soma das colunas: [12 15 18]
soma das linhas: [ 6 15 24]


##7. Operações com Dados Aleatórios:

In [ ]:
# Gerando dados aleatórios
dados_aleatorios = np.random.randn(1000)  # 1000 números aleatórios de uma distribuição normal padrão

# Calculando a média e o desvio padrão
media_aleatoria = np.mean(dados_aleatorios)
desvio_padrao_aleatorio = np.std(dados_aleatorios)
print(media_aleatoria)
print(desvio_padrao_aleatorio)

-0.008152918792340664
0.9850603932414146


##8. Manipulação de dados

In [ ]:
# Reshape para transformar um array unidimensional em uma matriz
arr = np.arange(12)
matriz = arr.reshape(3, 4)

# Transposição de uma matriz
matriz_transposta = matriz.T
print(matriz_transposta)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


##9. Produto Interno (Dot Product):

In [ ]:
# Produto interno de duas matrizes
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

produto_interno = np.dot(A, B)
print(produto_interno)

[[19 22]
 [43 50]]


##10.  Indexação Booleana e Filtragem:

In [ ]:
# Filtrando valores maiores que 10
dados = np.array([5, 12, 8, 15, 20, 7])
filtro = dados > 10
valores_maiores_que_10 = dados[filtro]
print(valores_maiores_que_10)

[12 15 20]


##Exemplo com array e matriz

In [ ]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:2, :2])

[['a' 'b']
 ['d' 'e']]


In [ ]:
a = np.arange(5)
#Após essa linha, a será um array NumPy unidimensional com os valores [0, 1, 2, 3, 4]
#Nesta linha, cada elemento do array a é somado a 20.
a + 20
print("matriz:", a)
print("matriz somada:", a + 20)

[0 1 2 3 4]
[20 21 22 23 24]


In [ ]:
#Numpy Boolean Arrays
a = np.arange(5)

print(a <= 3)

[ True  True  True  True False]


## Produto interno

In [ ]:
import numpy as np

# Criando dois arrays
arrayA = np.array([1, 2, 3])
arrayB = np.array([4, 5, 6])

# Calculando o produto interno
produto_interno = arrayA.dot(arrayB)

print("Array A:", arrayA)
print("Array B:", arrayB)
print("Produto Interno:", produto_interno)


##Produto interno e transporta

In [ ]:
import numpy as np

# Criando dois arrays
arrayA = np.array([1, 2, 3])
arrayB2 = np.array([[4, 5, 6], [7, 8, 9]])

# Calculando o produto interno
produto_interno1 = arrayA.dot(arrayB2.T)

# Transpondo o arrayB
transposta_arrayB2 = arrayB2.T

print("Array A:", arrayA)
print("Array B:", arrayB2)
print("Produto Interno (arrayA @ transposta_arrayB):")
print(produto_interno1)
print("Transposta de arrayB (arrayB.T):")
print(transposta_arrayB2)



Array A: [1 2 3]
Array B: [[4 5 6]
 [7 8 9]]
Produto Interno (arrayA @ transposta_arrayB):
[32 50]
Transposta de arrayB (arrayB.T):
[[4 7]
 [5 8]
 [6 9]]


##Algebra and size

In [ ]:
l = list(range(1000))
a = np.arange(1000)
%time np.sum(a ** 2)
%time sum([x **2 for x in l])

CPU times: user 306 µs, sys: 0 ns, total: 306 µs
Wall time: 316 µs
CPU times: user 484 µs, sys: 0 ns, total: 484 µs
Wall time: 494 µs


332833500

# PANDAS

In [ ]:
import pandas as pd


## Criando um Data-frame

In [ ]:
import pandas as pd
# Criando um DataFrame a partir de um dicionário
data = {'Nome': ['Alice', 'Bob', 'Charlie', 'Peter', 'Margot', 'Pimba'],
        'Idade': [25, 30, 35, 40, 60, 90],
        'Cidade': ['A', 'B', 'C', 'D', 'E', 'F']}
print("----DataFrame-----")
df = pd.DataFrame(data)
print(df)
print("------------------")
print("----Head----------")
# Visualizando as primeiras linhas do DataFrame
print(df.head(1))
print("------------------")
print("----idade---------")
# Selecionando uma coluna
idades = df['Idade']
print(idades)



----DataFrame-----
      Nome  Idade Cidade
0    Alice     25      A
1      Bob     30      B
2  Charlie     35      C
3    Peter     40      D
4   Margot     60      E
5    Pimba     90      F
------------------
----Head----------
    Nome  Idade Cidade
0  Alice     25      A
------------------
----idade---------
0    25
1    30
2    35
3    40
4    60
5    90
Name: Idade, dtype: int64


## Carregando dados de um csv

In [ ]:
# Carregando um DataFrame a partir de um arquivo CSV
df_csv = pd.read_csv('dados.csv')


## filtrando dados

In [ ]:
# Filtrando dados com base em uma condição
maiores_de_30 = df[df['Idade'] > 30]
print(maiores_de_30)

      Nome  Idade Cidade
2  Charlie     35      C
3    Peter     40      D
4   Margot     60      E
5    Pimba     90      F


## Estatisticas Descritivas

In [ ]:
# Calculando estatísticas descritivas
estatisticas = df.describe()
print(estatisticas)

           Idade
count   6.000000
mean   46.666667
std    24.426761
min    25.000000
25%    31.250000
50%    37.500000
75%    55.000000
max    90.000000


## Agrupando e agregando dados

In [ ]:
# Agrupando por uma coluna e calculando a média
media_por_cidade = df.groupby('Cidade')['Idade'].mean()
print(media_por_cidade)

Cidade
A    25.0
B    30.0
C    35.0
D    40.0
E    60.0
F    90.0
Name: Idade, dtype: float64


## Adicionando nova coluna

In [ ]:
import pandas as pd

# Criando um DataFrame de exemplo
data = {'Nome': ['Alice', 'Bob', 'Charlie'],
        'Idade': [25, 30, 35],
        'Cidade': ['A', 'B', 'C']}
df = pd.DataFrame(data)
print("Dataframe:")
print(df)

# Adicionando uma nova coluna
df['Nova_Coluna'] = df['Idade'] * 2

# Imprimindo a nova coluna
print("Nova Coluna:")
print(df['Nova_Coluna'])

# Visualizando o DataFrame com a nova coluna
print("\nNovo DataFrame:")
print(df)


Dataframe:
      Nome  Idade Cidade
0    Alice     25      A
1      Bob     30      B
2  Charlie     35      C
Nova Coluna:
0    50
1    60
2    70
Name: Nova_Coluna, dtype: int64

Novo DataFrame:
      Nome  Idade Cidade  Nova_Coluna
0    Alice     25      A           50
1      Bob     30      B           60
2  Charlie     35      C           70


## Exemplo de panda series

In [ ]:
import pandas as pd

certificates_earned = pd.Series(
    [8, 2, 5, 6],
    index=['Tom', 'Kris', 'Ahmad', 'Beau']
)

print(certificates_earned)

Tom      8
Kris     2
Ahmad    5
Beau     6
dtype: int64


#Pandas Indexing and Conditional Selection
Em Python, o atributo iloc é comumente associado à biblioteca pandas, que é amplamente utilizada para análise de dados e manipulação de conjuntos de dados tabulares. iloc é uma abreviação de "index location" e é usado para acessar os elementos de um DataFrame pelo índice numérico, em oposição ao índice baseado em rótulos

In [ ]:
import pandas as pd

data = {'Nome': ['Alice', 'Bob', 'Charlie', 'David'],
        'Idade': [25, 30, 35, 40],
        'Salário': [50000, 60000, 75000, 90000]}

df = pd.DataFrame(data)
print(df)
print("-------------------------------------------")

#Acessar a primeira linha do DataFrame:
primeira_linha = df.iloc[0]
print("primeira linha:", primeira_linha)

print("-------------------------------------------")

#Acessar o valor da segunda linha e da coluna 'Idade':
idade_bob = df.iloc[1]['Idade']
print("idade do bob:", idade_bob)
print("-------------------------------------------")

#Acessar um subconjunto do DataFrame (por exemplo, linhas de 1 a 2 e colunas de 0 a 1):
subset = df.iloc[1:3, 0:2]
print(subset)
print()
print("-------------------------------------------")
#df['Alice'] = 22
#df.iloc[-1] = 660 só  daria  assim se fosse uumam sserie
print(df)
print("-------------------------------------------")
#3Modificar um elemento específico usando iloc e índices numéricos:
# Modificar a idade de Bob para 31
df.iloc[1, df.columns.get_loc('Idade')] = 31
print(df)
print("-------------------------------------------")
#Modificar um elemento específico usando rótulos de coluna:
# Modificar o salário de Alice para 55000
df.at[0, 'Salário'] = 55000
print(df)
#O método at permite modificar um único valor com base em rótulos de linha e coluna.
print("-------------------------------------------")
#Modificar vários elementos simultaneamente:
# Modificar as idades de Charlie e David
df.loc[df['Nome'].isin(['Charlie', 'David']), 'Idade'] = [36, 41]
print(df)

      Nome  Idade  Salário
0    Alice     25    50000
1      Bob     30    60000
2  Charlie     35    75000
3    David     40    90000
-------------------------------------------
primeira linha: Nome       Alice
Idade         25
Salário    50000
Name: 0, dtype: object
-------------------------------------------
idade do bob: 30
-------------------------------------------
      Nome  Idade
1      Bob     30
2  Charlie     35

-------------------------------------------
      Nome  Idade  Salário
0    Alice     25    50000
1      Bob     30    60000
2  Charlie     35    75000
3    David     40    90000
-------------------------------------------
      Nome  Idade  Salário
0    Alice     25    50000
1      Bob     31    60000
2  Charlie     35    75000
3    David     40    90000
-------------------------------------------
      Nome  Idade  Salário
0    Alice     25    55000
1      Bob     31    60000
2  Charlie     35    75000
3    David     40    90000
----------------------------------

In [ ]:
import pandas as pd

certificates_earned = pd.Series(
    [8, 2, 5, 6],
    index=['Tom', 'Kris', 'Ahmad', 'Beau']
)
certificates_earned.iloc[-1] = 660
print(certificates_earned[certificates_earned > 5])




Tom       8
Beau    660
dtype: int64


# Panda DataFrames

In [ ]:
import pandas as pd

certificates_earned = pd.DataFrame({
    'Certificates': [8, 2, 5, 6],
    'Time (in months)': [16, 5, 9, 12]
})

certificates_earned.index = ['Tom', 'Kris', 'Ahmad', 'Beau']

print(certificates_earned.iloc[2])

Certificates        5
Time (in months)    9
Name: Ahmad, dtype: int64


In [ ]:
dataframe.columns
dataframe.index
dataframe.info()
dataframe.size
dataframe.shape
dataframe.describe()
dataframe.dtypes
dataframe.value_counts()

fala tambem sobre indexing, selection e slicing esse dataframe

In [ ]:
import pandas as pd

# Criando um DataFrame com dados fictícios
dados = {'Nome': ['Alice', 'Bob', 'Charlie', 'David'],
         'Idade': [25, 30, 35, 40],
         'Cidade': ['Rio de Janeiro', 'São Paulo', 'Belo Horizonte', 'Brasília'],
         'Salário': [50000, 60000, 75000, 90000]}

df = pd.DataFrame(dados)

# Exibindo o DataFrame
print("DataFrame original:")
print(df)
print("----------------------------------------------------------------")

# Métodos e conceitos:

# dataframe.columns
print("Colunas do DataFrame:")
print(df.columns)
print()
print("----------------------------------------------------------------")

# dataframe.index
print("Índices das linhas do DataFrame:")
print(df.index)
print()
print("----------------------------------------------------------------")
# dataframe.info()
print("Informações sobre o DataFrame:")
df.info()
print()
print("----------------------------------------------------------------")

# dataframe.size
print("Tamanho total do DataFrame:")
print(df.size)
print()
print("----------------------------------------------------------------")

# dataframe.shape
print("Dimensões do DataFrame (linhas, colunas):")
print(df.shape)
print()
print("----------------------------------------------------------------")

# dataframe.describe()
print("Estatísticas descritivas do DataFrame:")
print(df.describe())
print()
print("----------------------------------------------------------------")

# dataframe.dtypes
print("Tipos de dados das colunas do DataFrame:")
print(df.dtypes)
print()
print("----------------------------------------------------------------")
# dataframe.value_counts()
print("Contagem de valores únicos na coluna 'Cidade':")
print(df['Cidade'].value_counts())
print()
print("----------------------------------------------------------------")

# Indexing, Selection e Slicing:

# Indexing
print("Selecionando a coluna 'Idade' por rótulo de coluna:")
idade = df['Idade']
print(idade)
print()
print("----------------------------------------------------------------")

# Selection
print("Selecionando pessoas com salário superior a 70000:")
pessoas_salario_alto = df[df['Salário'] > 70000]
print(pessoas_salario_alto)
print()
print("----------------------------------------------------------------")
# Slicing
print("Slicing de linhas (índices 1 a 2):")
intervalo_linhas = df[1:3]
print(intervalo_linhas)
print()
print("----------------------------------------------------------------")

print("Slicing de colunas ('Nome' e 'Idade'):")
colunas_selecionadas = df[['Nome', 'Idade']]
print(colunas_selecionadas)
print("----------------------------------------------------------------")

DataFrame original:
      Nome  Idade          Cidade  Salário
0    Alice     25  Rio de Janeiro    50000
1      Bob     30       São Paulo    60000
2  Charlie     35  Belo Horizonte    75000
3    David     40        Brasília    90000
----------------------------------------------------------------
Colunas do DataFrame:
Index(['Nome', 'Idade', 'Cidade', 'Salário'], dtype='object')

----------------------------------------------------------------
Índices das linhas do DataFrame:
RangeIndex(start=0, stop=4, step=1)

----------------------------------------------------------------
Informações sobre o DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Nome     4 non-null      object
 1   Idade    4 non-null      int64 
 2   Cidade   4 non-null      object
 3   Salário  4 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 256.0+ bytes

------

In [ ]:
import pandas as pd

certificates_earned = pd.DataFrame({
    'Certificates': [8, 2, 5, 6],
    'Time (in months)': [16, 5, 9, 12]
})
names = ['Tom', 'Kris', 'Ahmad', 'Beau']

certificates_earned.index = names
longest_streak = pd.Series([13, 11, 9, 7], index=names)
certificates_earned['Longest streak'] = longest_streak

print(certificates_earned)

#realizar operações com as colunas do dataframe


       Certificates  Time (in months)  Longest streak
Tom               8                16              13
Kris              2                 5              11
Ahmad             5                 9               9
Beau              6                12               7


# Seleção condicional Pandas e modificação de dataframes

In [ ]:
import pandas as pd

# Criando um DataFrame com dados fictícios
dados = {'Nome': ['Alice', 'Bob', 'Charlie', 'David'],
         'Idade': [25, 30, 35, 40],
         'Cidade': ['Rio de Janeiro', 'São Paulo', 'Belo Horizonte', 'Brasília'],
         'Salário': [50000, 60000, 75000, 90000]}

df = pd.DataFrame(dados)

# Exibindo o DataFrame original
print("DataFrame original:")
print(df)
print()

# Seleção condicional com base em uma condição específica
print("Selecionando pessoas com idade superior a 30 anos:")
selecao_idade = df[df['Idade'] > 30]
print(selecao_idade)
print()

# Seleção condicional com base em múltiplas condições
print("Selecionando pessoas em São Paulo com salário superior a 60000:")
selecao_multipla = df[(df['Cidade'] == 'São Paulo') & (df['Salário'] > 60000)]
print(selecao_multipla)
print()

# Modificando valores em uma coluna com base em uma condição
print("Aumentando o salário das pessoas com idade superior a 30 anos em 10%:")
df.loc[df['Idade'] > 30, 'Salário'] *= 1.1
print(df)
print()

# Adicionando uma nova coluna ao DataFrame
df['Bônus'] = [2000, 2500, 3000, 3500]
print("Adicionando uma coluna 'Bônus' ao DataFrame:")
print(df)
print()

# Excluindo uma coluna do DataFrame
df = df.drop('Bônus', axis=1)
print("Removendo a coluna 'Bônus' do DataFrame:")
print(df)

# Excluindo linhas
df = df.drop(2)
print(df)

#================= realizando as mesmas operações mas com o loc=========
# Seleção condicional usando loc
print("Selecionando pessoas com idade superior a 30 anos:")
selecao_idade = df.loc[df['Idade'] > 30]
print(selecao_idade)
print()

# Seleção condicional com múltiplas condições usando loc
print("Selecionando pessoas em São Paulo com salário superior a 60000:")
selecao_multipla = df.loc[(df['Cidade'] == 'São Paulo') & (df['Salário'] > 60000)]
print(selecao_multipla)
print()

# Modificando valores em uma coluna com base em uma condição usando loc
print("Aumentando o salário das pessoas com idade superior a 30 anos em 10%:")
df.loc[df['Idade'] > 30, 'Salário'] *= 1.1
print(df)
print()

# Adicionando uma nova coluna ao DataFrame usando loc
df.loc[:, 'Bônus'] = [2000, 2500, 3000, 3500]
print("Adicionando uma coluna 'Bônus' ao DataFrame:")
print(df)
print()

# Excluindo uma coluna do DataFrame usando loc
df = df.drop('Bônus', axis=1)
print("Removendo a coluna 'Bônus' do DataFrame:")
print(df)

#--------------------------------------------
#pesquisar sobre operações com series, substituindo valore por coluna, renomeando colunas

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!git clone https://github.com/juliaNogueiraC/Estudos-em-Data-Analysis-Python

fatal: destination path 'Estudos-em-Data-Analysis-Python' already exists and is not an empty directory.


In [ ]:
%cd /content/drive/MyDrive/Estudos-em-Data-Analysis-Python.ipynb

[Errno 2] No such file or directory: '/content/drive/MyDrive/Estudos-em-Data-Analysis-Python.ipynb'
/content


In [ ]:
!git add .

fatal: not a git repository (or any of the parent directories): .git


In [ ]:
!git commit -m


fatal: not a git repository (or any of the parent directories): .git


In [ ]:
!git push origin main

fatal: not a git repository (or any of the parent directories): .git
